### ISSUE TITLE
[BUG] yarn 2 pnp issues

### ISSUE THREAD

**Issue by regevbr** [npm/git#3]
The library requires the lru-cache and semver packages but they are not declared as dependencies. 
This is done at https://github.com/npm/git/blob/308ca27765a71898b012a59e5aa6ecca507b0ade/lib/revs.js#L3 and https://github.com/npm/git/blob/308ca27765a71898b012a59e5aa6ecca507b0ade/lib/lines-to-revs.js#L4

Because yarn 2 uses PlugNPlay, it is not allowed to use non declared dependencies, causing my CI tools to fail

Temp fix is to add to .yarnrc.yml
```yaml
packageExtensions:
  "@npmcli/git@*":
    dependencies:
      lru-cache: "*"
      semver: "*"
```
